package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

// runBatsExportWith is the handler behind `glyph export bats`. The
// dispatcher in newExportCommand forwards the spec args and --out flag.
func runBatsExportWith(cmd *cobra.Command, opts *globalOptions, args []string, outPath string) error {
	if len(args) != 1 {
		return exitError{code: 2, err: fmt.Errorf("export bats expects exactly one <spec> argument")}
	}
	f, err := resolveFormat(opts.format)
	if err != nil {
		return exitError{code: 2, err: err}
	}
	source := args[0]
	out, err := exportBats(source, outPath)
	if err != nil {
		return exitError{code: 2, err: err}
	}
	output, err := emitForCLI(cmd, opts, f, out, func() string { return renderBatsExportMarkdown(out) })
	if err != nil {
		return exitError{code: 2, err: err}
	}
	cmd.Print(output)
	return nil
}

type batsExportResult struct {
	SourcePath string   `json:"sourcePath" yaml:"sourcePath"`
	OutputPath string   `json:"outputPath" yaml:"outputPath"`
	Tests      int      `json:"tests" yaml:"tests"`
	Warnings   []string `json:"warnings,omitempty" yaml:"warnings,omitempty"`
	Bats       string   `json:"bats" yaml:"bats"`
}

func exportBats(source string, outPath string) (batsExportResult, error) {
	data, err := os.ReadFile(source)
	if err != nil {
		return batsExportResult{}, err
	}
	// Reuse the parseSpec path indirectly: the bats exporter only needs
	// a coarse view of the spec, so a simple yaml.Unmarshal into a
	// shim is enough. For now we don't need full step-by-step fidelity;
	// we emit one @test per outcome, with the target command as the
	// test body and the outcome's command-verifier as the assertion.
	var shim struct {
		Version  int    `yaml:"version"`
		Name     string `yaml:"name"`
		Intent   string `yaml:"intent"`
		Metadata struct {
			Feature  string   `yaml:"feature"`
			Priority string   `yaml:"priority"`
			Tags     []string `yaml:"tags"`
		} `yaml:"metadata"`
		Target struct {
			Cmd []string `yaml:"cmd"`
		} `yaml:"target"`
		Outcomes []struct {
			ID          string `yaml:"id"`
			Description string `yaml:"description"`
			Verify      struct {
				Command *struct {
					Run       string `yaml:"run"`
					TimeoutMS int    `yaml:"timeoutMs"`
				} `yaml:"command"`
				Screen *struct {
					Contains    string `yaml:"contains"`
					NotContains string `yaml:"notContains"`
					Regex       string `yaml:"regex"`
				} `yaml:"screen"`
			} `yaml:"verify"`
		} `yaml:"outcomes"`
	}
	if err := yaml.Unmarshal(data, &shim); err != nil {
		return batsExportResult{}, fmt.Errorf("parse spec: %w", err)
	}
	if shim.Version != 1 {
		return batsExportResult{}, fmt.Errorf("unsupported spec version: %d", shim.Version)
	}
	if outPath == "" {
		outPath = strings.TrimSuffix(source, filepath.Ext(source)) + ".bats"
	}
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bats\n")
	fmt.Fprintf(&b, "# Generated by `glyph export bats %s`. Re-run the exporter\n", filepath.Base(source))
	fmt.Fprintf(&b, "# to refresh this file after editing the source.\n")
	if shim.Intent != "" {
		fmt.Fprintf(&b, "# Intent: %s\n", oneLine(shim.Intent))
	}
	if shim.Metadata.Feature != "" {
		fmt.Fprintf(&b, "# Feature: %s\n", shim.Metadata.Feature)
	}
	for _, tag := range shim.Metadata.Tags {
		fmt.Fprintf(&b, "# Tag: %s\n", tag)
	}
	b.WriteString("\n")
	targetCmd := strings.Join(shim.Target.Cmd, " ")
	for i, oc := range shim.Outcomes {
		testName := oc.ID
		if testName == "" {
			testName = fmt.Sprintf("outcome_%d", i+1)
		}
		fmt.Fprintf(&b, "@test \"%s\" {\n", testName)
		if oc.Description != "" {
			fmt.Fprintf(&b, "  # %s\n", oneLine(oc.Description))
		}
		switch {
		case oc.Verify.Command != nil:
			fmt.Fprintf(&b, "  run %s\n", targetCmd)
			b.WriteString("  [ \"$status\" -eq 0 ]\n")
		case oc.Verify.Screen != nil:
			fmt.Fprintf(&b, "  # TODO: glyphrun screen verifier — adapt for bats\n")
			fmt.Fprintf(&b, "  run %s\n", targetCmd)
			b.WriteString("  [ \"$status\" -eq 0 ]\n")
		default:
			fmt.Fprintf(&b, "  # TODO: glyphrun-only outcome verifier\n")
			fmt.Fprintf(&b, "  run %s\n", targetCmd)
			b.WriteString("  [ \"$status\" -eq 0 ]\n")
		}
		b.WriteString("}\n\n")
	}
	if err := os.WriteFile(outPath, []byte(b.String()), 0o755); err != nil {
		return batsExportResult{}, fmt.Errorf("write bats: %w", err)
	}
	return batsExportResult{
		SourcePath: source,
		OutputPath: outPath,
		Tests:      len(shim.Outcomes),
		Bats:       b.String(),
	}, nil
}

func renderBatsExportMarkdown(r batsExportResult) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Glyphrun Bats Export\n\n")
	fmt.Fprintf(&b, "- source: `%s`\n", r.SourcePath)
	fmt.Fprintf(&b, "- output: `%s`\n", r.OutputPath)
	fmt.Fprintf(&b, "- tests exported: %d\n", r.Tests)
	if len(r.Warnings) > 0 {
		b.WriteString("\n## Warnings\n\n")
		for _, w := range r.Warnings {
			fmt.Fprintf(&b, "- %s\n", w)
		}
	}
	return b.String()
}

// oneLine collapses multi-line strings to a single line for use in a
// bats comment header.
func oneLine(s string) string {
	s = strings.TrimSpace(s)
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", "")
	if len(s) > 80 {
		return s[:77] + "..."
	}
	return s
}
