// Package ghreport renders GitHub-flavored Markdown summarizing run results.
//
// It lives outside internal/cli so the PR-comment formatting — the product's
// CI-facing output — is testable on its own, keeping `glyph comment` a thin
// handler that resolves run dirs and writes the rendered Markdown.
package ghreport

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/abdul-hamid-achik/glyphrun/internal/artifacts"
)

// RecentRunDirs returns the n newest run directories under root, newest first.
// Ordering is by modification time rather than name, because `record-*` run
// dirs do not share the timestamped naming of `glyph run` dirs.
func RecentRunDirs(root string, n int) ([]string, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, err
	}
	type runDir struct {
		path string
		mod  int64
	}
	var dirs []runDir
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		info, err := e.Info()
		if err != nil {
			continue
		}
		dirs = append(dirs, runDir{path: filepath.Join(root, e.Name()), mod: info.ModTime().UnixNano()})
	}
	sort.Slice(dirs, func(i, j int) bool { return dirs[i].mod > dirs[j].mod })
	if n < len(dirs) {
		dirs = dirs[:n]
	}
	out := make([]string, 0, len(dirs))
	for _, d := range dirs {
		out = append(out, d.path)
	}
	return out, nil
}

// Render builds GitHub-flavored Markdown summarizing the given runs: a status
// table, per-failure detail with the final screen folded into a <details>
// block, and pointers to the deterministic SVG screenshots.
func Render(results []artifacts.RunResult) string {
	if len(results) == 0 {
		return "## Glyphrun\n\nNo runs found.\n"
	}
	var b strings.Builder
	allPassed := true
	for _, r := range results {
		if r.Status != artifacts.StatusPassed {
			allPassed = false
		}
	}
	badge := "✅ passed"
	if !allPassed {
		badge = "❌ failed"
	}
	fmt.Fprintf(&b, "## Glyphrun — %s\n\n", badge)

	b.WriteString("| Spec | Status | Outcomes | Exit | Duration |\n")
	b.WriteString("|---|---|---|---|---|\n")
	for _, r := range results {
		passed, failed := 0, 0
		for _, o := range r.Outcomes {
			if o.Status == artifacts.OutcomePassed {
				passed++
			} else {
				failed++
			}
		}
		mark := "✅"
		if r.Status != artifacts.StatusPassed {
			mark = "❌"
		}
		fmt.Fprintf(&b, "| `%s` | %s %s | %d✓ %d✗ | %d | %dms |\n",
			r.SpecName, mark, r.Status, passed, failed, r.ExitCode, r.DurationMS)
	}
	b.WriteByte('\n')

	for _, r := range results {
		if r.Status == artifacts.StatusPassed {
			continue
		}
		fmt.Fprintf(&b, "### ❌ %s\n\n", r.SpecName)
		for _, o := range r.Outcomes {
			if o.Status == artifacts.OutcomePassed {
				continue
			}
			fmt.Fprintf(&b, "- `%s`", o.ID)
			if o.Message != "" {
				fmt.Fprintf(&b, ": %s", o.Message)
			}
			b.WriteByte('\n')
		}
		b.WriteByte('\n')
		if screen := readRunScreen(r); screen != "" {
			b.WriteString("<details><summary>Final screen</summary>\n\n```text\n")
			b.WriteString(screen)
			b.WriteString("\n```\n\n</details>\n\n")
		}
		if r.Artifacts["finalScreenSVG"] != "" {
			fmt.Fprintf(&b, "Screenshot: `%s/%s` · ", filepath.Base(r.RunDir), r.Artifacts["finalScreenSVG"])
		}
		if r.Artifacts["agentContext"] != "" {
			fmt.Fprintf(&b, "Context: `%s/%s`", filepath.Base(r.RunDir), r.Artifacts["agentContext"])
		}
		b.WriteString("\n\n")
	}

	b.WriteString("<sub>Generated by `glyph comment`.</sub>\n")
	return b.String()
}

func readRunScreen(r artifacts.RunResult) string {
	rel := r.Artifacts["finalScreenText"]
	if rel == "" {
		rel = "screens/final.txt"
	}
	data, err := os.ReadFile(filepath.Join(r.RunDir, rel))
	if err != nil {
		return ""
	}
	return strings.TrimRight(string(data), "\n")
}
