// Package scaffold turns a recorded PTY session into a draft spec.
//
// It lives outside internal/cli so the logic — inferring a representative
// "ready" string, building the spec, stamping its contract hash — is testable
// without a cobra command, keeping the CLI handler a thin wrapper.
package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	"github.com/abdul-hamid-achik/glyphrun/internal/config"
	"github.com/abdul-hamid-achik/glyphrun/internal/ptyrunner"
	"github.com/abdul-hamid-achik/glyphrun/internal/spec"
	"gopkg.in/yaml.v3"
)

// Params describes a recorded session to scaffold a spec from.
type Params struct {
	Path        string // where to write the draft spec
	Argv        []string
	Cwd         string
	Terminal    spec.Terminal
	FinalScreen string
	Exit        ptyrunner.ExitState
	ConfigPath  string
	Environment string
}

// Result summarizes what FromSession produced.
type Result struct {
	Path      string `json:"path" yaml:"path"`
	Name      string `json:"name" yaml:"name"`
	Ready     string `json:"ready,omitempty" yaml:"ready,omitempty"`
	Stamped   bool   `json:"stamped" yaml:"stamped"`
	NeedsEdit bool   `json:"needsEdit" yaml:"needsEdit"`
}

// FromSession writes a draft spec at p.Path and stamps its contract hash so it
// is immediately runnable. The draft captures the observable contract — a
// representative "ready" string and the exit code — as outcomes; interaction
// steps are left for the author to fill in, since recording does not capture
// input. The contract is what matters; steps are repairable hints.
func FromSession(p Params) (*Result, error) {
	name := deriveSpecName(p.Argv)
	draft, ready, needsEdit := buildSpec(name, p.Argv, p.Cwd, p.Terminal, p.FinalScreen, p.Exit)

	data, err := yaml.Marshal(draft)
	if err != nil {
		return nil, err
	}
	if dir := filepath.Dir(p.Path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return nil, err
		}
	}
	header := "# Generated by `glyph record --scaffold`. Edit freely: `steps` are\n" +
		"# repairable hints, `intent` and `outcomes` are the behavior contract.\n" +
		"# After editing intent/outcomes, re-stamp with `glyph spec verify --stamp`.\n"
	if err := os.WriteFile(p.Path, append([]byte(header), data...), 0o644); err != nil {
		return nil, err
	}

	result := &Result{Path: p.Path, Name: name, Ready: ready, NeedsEdit: needsEdit}

	// Stamp the contract hash so the draft runs without an immediate exit-6.
	// A draft that can't be parsed (shouldn't happen) is still left on disk
	// for the author; we just report that it wasn't stamped.
	rt, err := config.LoadRuntime(p.Path, p.ConfigPath, p.Environment)
	if err != nil {
		return result, nil
	}
	parseOpts := rt.SpecParseOptions()
	parseOpts.AllowHashMismatch = true
	parsed, err := spec.ParseFile(p.Path, parseOpts)
	if err != nil {
		return result, nil
	}
	if err := spec.StampContractHash(parsed.Path, parsed.ContractHash); err != nil {
		return result, nil
	}
	result.Stamped = true
	return result, nil
}

// buildSpec assembles the draft spec. It returns the spec, the inferred ready
// string (may be empty), and whether the author still needs to fill in a real
// assertion.
func buildSpec(name string, argv []string, cwd string, term spec.Terminal, finalScreen string, exit ptyrunner.ExitState) (spec.Spec, string, bool) {
	ready := pickReadyLine(finalScreen)
	var steps []spec.Step
	var outcomes []spec.Outcome

	if ready != "" {
		steps = append(steps,
			spec.Step{Wait: &spec.WaitStep{Screen: &spec.ScreenCondition{Contains: ready}, TimeoutMS: 5000}},
			spec.Step{Snapshot: "home"},
		)
		outcomes = append(outcomes, spec.Outcome{
			ID:          "ready_visible",
			Description: "the app reaches its ready state",
			Verify:      spec.Verify{Screen: &spec.ScreenCondition{Contains: ready}},
		})
	}
	// Only assert the exit code when the process exited on its own. A negative
	// code means glyphrun killed it (timeout / interrupt), which is an artifact
	// of recording, not a behavior contract.
	if exit.Exited && exit.ExitCode >= 0 {
		code := exit.ExitCode
		outcomes = append(outcomes, spec.Outcome{
			ID:          "clean_exit",
			Description: fmt.Sprintf("the app exits with code %d", code),
			Verify:      spec.Verify{Process: &spec.ProcessCondition{ExitCode: &code}},
		})
	}

	needsEdit := false
	if len(outcomes) == 0 {
		// Nothing observable to assert (e.g. a screen with no text and no
		// exit). Emit a placeholder so the spec parses, and flag it.
		needsEdit = true
		const placeholder = "REPLACE_ME"
		steps = append(steps, spec.Step{Wait: &spec.WaitStep{Screen: &spec.ScreenCondition{Contains: placeholder}, TimeoutMS: 5000}})
		outcomes = append(outcomes, spec.Outcome{
			ID:          "ready_visible",
			Description: "TODO: assert a string the app renders",
			Verify:      spec.Verify{Screen: &spec.ScreenCondition{Contains: placeholder}},
		})
	}

	s := spec.Spec{
		Version:  1,
		Name:     name,
		Intent:   fmt.Sprintf("a user can run %s and it reaches its expected state.\n", strings.Join(argv, " ")),
		Target:   spec.Target{Cmd: argv, Cwd: cwd},
		Terminal: term,
		Steps:    steps,
		Outcomes: outcomes,
	}
	return s, ready, needsEdit
}

// pickReadyLine chooses a representative "ready" string from the final screen:
// the first non-empty line that contains a letter, capped to a reasonable
// length. Border and separator rows (no letters) are skipped.
func pickReadyLine(finalScreen string) string {
	for _, raw := range strings.Split(finalScreen, "\n") {
		line := strings.TrimSpace(raw)
		if len([]rune(line)) < 3 {
			continue
		}
		if !strings.ContainsFunc(line, unicode.IsLetter) {
			continue
		}
		runes := []rune(line)
		if len(runes) > 50 {
			line = strings.TrimSpace(string(runes[:50]))
		}
		return line
	}
	return ""
}

// deriveSpecName builds a snake_case spec name from the recorded command's
// program name, e.g. ["./bin/hello", "--flag"] -> "hello_smoke".
func deriveSpecName(argv []string) string {
	base := "recorded"
	if len(argv) > 0 && argv[0] != "" {
		base = filepath.Base(argv[0])
		base = strings.TrimSuffix(base, filepath.Ext(base))
	}
	var b strings.Builder
	lastUnderscore := false
	for _, r := range strings.ToLower(base) {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			lastUnderscore = false
		default:
			if !lastUnderscore {
				b.WriteByte('_')
				lastUnderscore = true
			}
		}
	}
	name := strings.Trim(b.String(), "_")
	if name == "" {
		name = "recorded"
	}
	if name[0] >= '0' && name[0] <= '9' {
		name = "spec_" + name
	}
	return name + "_smoke"
}
